"""Add three columns: is_active, deleted_at and deleted_by in orders table

Revision ID: 0bc2afc8c580
Revises: 5537ed04ae2a
Create Date: 2025-11-28 21:33:53.254591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bc2afc8c580'
down_revision: Union[str, Sequence[str], None] = '5537ed04ae2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('audit_log', sa.Column('actor_username', sa.Text(), nullable=False))
    op.add_column('audit_log', sa.Column('full_name', sa.String(length=150), nullable=False))
    op.add_column('audit_log', sa.Column('details', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_audit_log_table_record'), table_name='audit_log')
    op.create_index(op.f('ix_audit_log_log_id'), 'audit_log', ['log_id'], unique=False)
    op.drop_constraint(op.f('audit_log_actor_id_fkey'), 'audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'audit_log', 'users', ['user_id'], ['user_id'])
    op.drop_column('audit_log', 'actor_name')
    op.drop_column('audit_log', 'old_data')
    op.drop_column('audit_log', 'actor_id')
    op.drop_column('audit_log', 'new_data')
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('audit_log', sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_log', sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_log', sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_log', sa.Column('actor_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('audit_log_actor_id_fkey'), 'audit_log', 'users', ['actor_id'], ['user_id'])
    op.drop_index(op.f('ix_audit_log_log_id'), table_name='audit_log')
    op.create_index(op.f('ix_audit_log_table_record'), 'audit_log', ['table_name', 'record_id'], unique=False)
    op.drop_column('audit_log', 'details')
    op.drop_column('audit_log', 'full_name')
    op.drop_column('audit_log', 'actor_username')
    op.drop_column('audit_log', 'user_id')
    # ### end Alembic commands ###
