"""Change some trigger to improve the clearly and clean of the tables

Revision ID: 3cd62fc5971b
Revises: 8c94e09187a6
Create Date: 2025-11-26 19:05:09.228932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd62fc5971b'
down_revision: Union[str, Sequence[str], None] = '8c94e09187a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_audit_log_log_id'), 'audit_log', ['log_id'], unique=False)
    op.drop_column('audit_log', 'actor_username')
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('audit_log', sa.Column('actor_username', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_audit_log_log_id'), table_name='audit_log')
    op.alter_column('audit_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
