"""new migration adding audit table and triggers to manage functionality

Revision ID: 8c94e09187a6
Revises: 8a3a7ad1e2ef
Create Date: 2025-11-26 09:22:19.849935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c94e09187a6'
down_revision: Union[str, Sequence[str], None] = '8a3a7ad1e2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema (no-op).

    This revision previously attempted to drop the audit_log table and the
    products.is_active column. Both actions are destructive and conflict with
    the application's soft-delete and auditing logic. Leaving this upgrade as
    a no-op to preserve existing behavior.
    """
    # Intentionally no-op


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Leaving downgrade as no-op as well to avoid destructive changes.
    pass
    # ### end Alembic commands ###
